# Generated by Django 4.2 on 2023-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='img_src',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='species',
            table='gallery',
        ),
    ]
