# Generated by Django 4.2 on 2023-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp', '0002_alter_species_img_src_alter_species_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='type',
            new_name='sort',
        ),
        migrations.AlterField(
            model_name='snp',
            name='MAF',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='snp',
            name='alter_allele',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='snp',
            name='ref_allele',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('C', 'C'), ('G', 'G'), ('T', 'T')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('sort', 'snp')},
        ),
    ]
