# Generated by Django 4.2 on 2023-06-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snp', '0003_rename_type_annotation_sort_alter_snp_maf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snp',
            old_name='species_name',
            new_name='species',
        ),
    ]
