# Generated by Django 4.2 on 2023-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp', '0004_rename_species_name_snp_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='MAF',
            field=models.FloatField(default=0.0),
        ),
    ]
